ci: create release workflow
qiujiangkun/kafcat pull request #19
Opened 2022-04-17 02:32 UTC by neverchanje

https://github.com/marketplace/actions/rust-release-binary

We may use this action to create binary release, so that users can download prebuilts rather than build from source.

2022-04-17 04:49 UTC, qiujiangkun commented
We can `cargo publish` to crates.io, not sure about GitHub releases. Install it by `cargo install kafcat`. I'll give other consideration

2022-04-17 05:01 UTC, neverchanje commented
Yes but `cargo install kafcat` basically compiles everything from the source. It is not convenient compared to downloading binaries.

2022-04-17 05:02 UTC, qiujiangkun commented
I'm fine with binary releases. How many platforms do we support in this CI?

2022-04-17 05:03 UTC, qiujiangkun requested changes
I want to support x86_64 windows, gnu linux, musl linux, maybe arm linux, x86 macos and aarch64 macos

2022-04-17 13:32 UTC, merged

2022-04-17 13:33 UTC, qiujiangkun commented
Merge the PR for now. Maybe add support for these triples later

2022-04-18 01:28 UTC, neverchanje commented
Ok thanks, sorry for late reply, I'm not 100% sure that rdkafka can be released in windows. Let me test macOS and Linux first.